<a href="https://colab.research.google.com/github/sc-mari-a/MN/blob/main/%D0%94%D0%BE%D1%80%D0%BE%D1%88%D0%B5%D0%BD%D0%BA%D0%BE_%D0%BF%D1%80_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота 1. Вступ до машинного навчання. Елементи лінійної алгебри.

## **Варіант № 5**

[Посилання на GitHub](...)


In [2]:
import numpy as np
np.__version__

'2.0.2'

**Завдання 1**

5. Створіть одновимірний масив (вектор) зі зворотнім порядком перших 10 натуральних чисел та виведіть його значення.

In [17]:
m = np.arange(10, 0, -1) # крок -1, щоб було в зворотньому порядку
print(m)

[10  9  8  7  6  5  4  3  2  1]


**Завдання 2**

5. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його послідовністю чисел, де кожне наступне число менше попереднього на 3, та виведіть його значення.

In [9]:
m2 = np.arange(27, 0, -3).reshape(3, 3) # починаємо з 27, бо нам потрібно 9 чисел (кожне 3 число)
m2

array([[27, 24, 21],
       [18, 15, 12],
       [ 9,  6,  3]])

**Завдання 3**

5. Створіть масив розміром 3x3, заповніть його випадковими дійсними числами від 0 до 1 та виведіть його значення.

In [13]:
m3 = np.random.rand(3, 3)
m3

array([[0.11784018, 0.44973761, 0.71246644],
       [0.01348249, 0.70391739, 0.06921897],
       [0.90966684, 0.12630506, 0.87925694]])

**Завдання 4**

5. Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та обчисліть добуток всіх елементів.

In [19]:
m4 = np.random.rand(3, 3)
print("Матриця:\n", m4)
print("\nДобуток всіх елементів:", np.prod(m4))

Матриця:
 [[0.36319015 0.33237759 0.19028925]
 [0.40132633 0.87554207 0.31812501]
 [0.71591925 0.88536398 0.64428397]]

Добуток всіх елементів: 0.0010486142466898881


**Завдання 5**

5. Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від -20 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.

In [21]:
m5_1 = np.random.randint(-20, 21, 6)
m5_2 = np.random.randint(-20, 21, 6)
print("Матриця 1:", m5_1, "\nМатриця 2:", m5_2)
print("\nДодавання матриць:", m5_1+m5_2, "\nВіднімання:", m5_1-m5_2, "\nМноження:", m5_1*m5_2)

Матриця 1: [-15  -8  11   9  12  14] 
Матриця 2: [ 10  -4  -1   1 -18  13]

Додавання матриць: [ -5 -12  10  10  -6  27] 
Віднімання: [-25  -4  12   8  30   1] 
Множення: [-150   32  -11    9 -216  182]


**Завдання 6**

5. Створіть дві матриці 2x2, заповніть їх довільними цілими числами від 6 до 10 та знайдіть їх добуток.

In [25]:
m6_1 = np.random.randint(6, 11, (2,2))
m6_2 = np.random.randint(6, 11, (2,2))
print("Матриця 1:\n", m6_1, "\nМатриця 2:\n", m6_2)
print("\nДобуток:\n", np.dot(m6_1, m6_2)) #добуток матриць,а не їх елементів

Матриця 1:
 [[10  9]
 [ 9  6]] 
Матриця 2:
 [[7 9]
 [6 9]]

Добуток:
 [[124 171]
 [ 99 135]]


**Завдання 7**

5. Створіть дві матриці розміром 3x2 та 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 8 та перемножте їх між собою.

In [26]:
m7_1 = np.random.randint(1, 9, (3,2))
m7_2 = np.random.randint(1, 9, (2,2))
print("Матриця 1:\n", m7_1, "\nМатриця 2:\n", m7_2)
print("\nДобуток:\n", np.dot(m7_1, m7_2))

Матриця 1:
 [[2 8]
 [4 7]
 [1 7]] 
Матриця 2:
 [[5 7]
 [5 4]]

Добуток:
 [[50 46]
 [55 56]
 [40 35]]


**Завдання 8**

5. Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [ ]:
m8 = np.random.randint(1, 11, (2,2))
print("Матриця:\n", m8)
print("Обернена матриця:\n", np.linalg.inv(m8))

**Завдання 9**

5. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 0 до 1 та транспонуйте її.

In [29]:
m9 = np.random.randint(0, 2, (3,3))
print("Матриця:\n", m9)
print("\nТранспонована:\n", m9.T)

Матриця:
 [[1 0 0]
 [0 1 1]
 [1 0 1]]

Транспонована:
 [[1 0 1]
 [0 1 0]
 [0 1 1]]


**Завдання 10**

5. Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [31]:
m10 = np.random.rand(3,4)
v10 = np.random.randint(1, 11, (4,1))
print("Матриця:\n", m10, "\nВектор:\n", v10)
print("\nДобуток матриці на вектор:\n", np.dot(m10, v10))

Матриця:
 [[0.41185776 0.05368235 0.4295018  0.34170161]
 [0.08712862 0.11389158 0.38896407 0.70011418]
 [0.17098267 0.45429179 0.92439748 0.19252901]] 
Вектор:
 [[8]
 [9]
 [8]
 [9]]

Добуток матриці на вектор:
 [[10.28933207]
 [11.13479331]
 [14.58442836]]


**Завдання 11**

5. Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [33]:
m11 = np.random.randint(1, 11, (2,3))
v11 = np.random.randint(1, 11, (3,1))
print("Матриця:\n", m11, "\nВектор:\n", v11)
print("\nДобуток матриці на вектор:\n", np.dot(m11, v11))

Матриця:
 [[ 6 10  7]
 [ 3  3  9]] 
Вектор:
 [[1]
 [9]
 [5]]

Добуток матриці на вектор:
 [[131]
 [ 75]]


**Завдання 12**

5. Створіть дві матриці розміром 6x6, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню суму.

In [35]:
m12_1 = np.random.randint(1, 11, (6,6))
m12_2 = np.random.randint(1, 11, (6,6))
print("Матриця 1:\n", m12_1, "\nМатриця 2:\n", m12_2)
print("\nCума матриць:\n", m12_1+m12_2)

Матриця 1:
 [[ 3  5  2  6  6  7]
 [ 9  5  6  3 10  5]
 [ 6  1  9  7  8  6]
 [ 8  4  1  6  2  3]
 [ 7  4  7  4  8  1]
 [10  4  7  9  2  8]] 
Матриця 2:
 [[ 4  7  6  8  7  2]
 [ 1  7  8  1  3  8]
 [ 4 10  4 10  3  9]
 [ 4  7 10  8 10 10]
 [ 9  1  1 10  5  7]
 [ 4  5  9  7  8  3]]

Cума матриць:
 [[ 7 12  8 14 13  9]
 [10 12 14  4 13 13]
 [10 11 13 17 11 15]
 [12 11 11 14 12 13]
 [16  5  8 14 13  8]
 [14  9 16 16 10 11]]


**Завдання 13**

5. Створіть дві матриці розміром 6x6, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть різницю їх елементів.

In [37]:
m13_1 = np.random.rand(6,6)
m13_2 = np.random.rand(6,6)
print("Матриця 1:\n", m13_1, "\nМатриця 2:\n", m13_2)
print("\nРізниця матриць:\n", m13_1-m13_2)

Матриця 1:
 [[0.52951426 0.57138659 0.30047426 0.5970629  0.4784008  0.52478859]
 [0.43243991 0.5108223  0.77368939 0.57769223 0.29352971 0.94476098]
 [0.15090119 0.41997311 0.37516469 0.48528928 0.83402995 0.68283225]
 [0.53761664 0.32480891 0.60446293 0.88238192 0.79562658 0.6442251 ]
 [0.91112304 0.3820205  0.58461709 0.51002359 0.54285175 0.59215941]
 [0.38758562 0.58007915 0.0091837  0.83507238 0.28012711 0.15925894]] 
Матриця 2:
 [[0.69732147 0.75049897 0.89238224 0.33207988 0.01147849 0.54120713]
 [0.35269413 0.51159246 0.78342416 0.07694875 0.23090442 0.32011676]
 [0.87494858 0.94762952 0.72733179 0.10250376 0.31998258 0.4075669 ]
 [0.97518795 0.65211703 0.70574246 0.16540561 0.64879425 0.52148472]
 [0.07876835 0.97651978 0.87195345 0.76149382 0.23596873 0.39867952]
 [0.11120882 0.22351566 0.97125998 0.94903957 0.48010014 0.80463526]]

Різниця матриць:
 [[-1.67807217e-01 -1.79112373e-01 -5.91907976e-01  2.64983020e-01
   4.66922315e-01 -1.64185422e-02]
 [ 7.97457773e-02 -7.7015

**Завдання 14**

5. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -5 до 5 та знайдіть добуток елементів матриці.

In [39]:
m14 = np.random.uniform(-5, 5, (3,3))
print("Матриця:\n", m14)
print("\nДобуток елементів:", np.prod(m14))

Матриця:
 [[-2.90704037 -1.2582101   3.5871899 ]
 [ 0.43098076  2.75073136 -3.48481525]
 [ 1.99181973 -1.64866009 -0.42988709]]

Добуток елементів: -76.52088410813313


**Завдання 15**

5. Створіть матрицю розміром 7x7, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить найбільший елемент у кожному рядку матриці.

In [40]:
m15 = np.random.rand(7,7)
v15 = np.max(m15, axis=1).reshape(-1,1) # axis=1 - для пошуку в рядку, і змінюємо розмір на вертекальний(стовпчик)
print("Матриця:\n", m15)
print("\nВектор-стовпчик:\n", v15)

Матриця:
 [[0.49260245 0.86683473 0.80796926 0.19883685 0.51718424 0.13326969
  0.1422249 ]
 [0.82704775 0.02311697 0.51928009 0.73752431 0.26589769 0.45304553
  0.9979078 ]
 [0.858346   0.93888173 0.39183127 0.65190728 0.12356055 0.76993526
  0.45792981]
 [0.32509902 0.42016149 0.92478876 0.68062089 0.24561972 0.22745562
  0.69376764]
 [0.09735541 0.47327035 0.15224522 0.06463162 0.80228313 0.16651735
  0.76184893]
 [0.18222114 0.42752439 0.01869662 0.87880215 0.40371327 0.42684951
  0.18503976]
 [0.82009241 0.35783101 0.40500968 0.4123387  0.58710966 0.86257838
  0.52147809]]

Вектор-стовпчик:
 [[0.86683473]
 [0.9979078 ]
 [0.93888173]
 [0.92478876]
 [0.80228313]
 [0.87880215]
 [0.86257838]]


# Висновок

В даній лабораторній роботі було використано методи, з бібліотеки numpy, для створення і роботи з матрицями та векторами. Використовувалися такі функції:
- np.arange – послідовність(вектор, якщо не змінювати розмір) чисел із заданим початком, кінцем та кроком

- np.random – генерації випадкових чисел (цілих або дійсних)

- .reshape – змінює форму

- .T – транспонування

- знаки +, -, * – виконують операції між масивами по елементам

- np.dot – множення матриць

- np.prod – добуток усіх елементів масиву

- np.max – максимальне значення у масиві (можна по всьому масиву чи по рядках(axis=1)/стовпцях(axis=0))

- np.linalg.inv – обернена матриця